name: pro_shop_golf_club
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  flutter_datetime_picker: ^1.5.1
  google_nav_bar: ^5.0.5
  intl: ^0.17.0
  internet_connection_checker: ^0.0.1+2
  intl_phone_number_input: ^0.7.0+2
  progress_dialog:
      git:
        url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_bloc: ^8.0.1
  emojis: ^0.9.9
  flutter_rating_bar: ^4.0.0
  change_app_package_name: ^1.0.0
  pinput: ^2.1.4
  cloud_firestore: ^3.1.6
  connectivity: ^3.0.6
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
