// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxlglPZA7cw0m8tF7NDVnEKRHnP51aYQ',
    appId: '1:453725375610:web:b400d0ddb0581321a57fc3',
    messagingSenderId: '453725375610',
    projectId: 'golfhub-de75f',
    authDomain: 'golfhub-de75f.firebaseapp.com',
    storageBucket: 'golfhub-de75f.appspot.com',
    measurementId: 'G-EZM9TM1D4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsmiafb6t2mruW0WNJCv9BV-ZCnNJtNic',
    appId: '1:453725375610:android:a5ef013e012a0b0ea57fc3',
    messagingSenderId: '453725375610',
    projectId: 'golfhub-de75f',
    storageBucket: 'golfhub-de75f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmWVvNADgMna3jAJ3Ple1cAoJWSr7IYE',
    appId: '1:453725375610:ios:847b74f44910d07fa57fc3',
    messagingSenderId: '453725375610',
    projectId: 'golfhub-de75f',
    storageBucket: 'golfhub-de75f.appspot.com',
    iosClientId: '453725375610-8kcar67krgl0h39ulqjp9o1lg3hl0802.apps.googleusercontent.com',
    iosBundleId: 'com.example.proShopGolfClub',
  );
}
